(() => {
  // Keep frequently tuned gameplay values in this small file so animation,
  // collision, and level-tuning changes do not create large game.js conflicts.
  window.IndiePlatformerConfig = Object.freeze({
    gravity: 1200,
    jumpVelocity: -480,
    maxFallSpeed: 900,
    walkSpeed: 230,
    runSpeed: 340,
    crouchSpeed: 120,
    playerWidth: 24,
    crouchHeight: 34,
    standHeight: 50,
    playerVisualScale: 1.17,
    walkerWidth: 32,
    walkerHeight: 28,
    walkerVisualScale: 0.78,
    droneWidth: 32,
    droneHeight: 28,
    droneDetectionRange: 440,
    droneFireCooldown: 1.85,
    droneWindup: 0.34,
    droneProjectileSpeed: 360,
    droneProjectileSize: 10,
    jumperLeapImpulse: 520,
    pulseCooldown: 0.35,
    pulseDamage: 1,
    pulseThickness: 5,
    pulseLifetime: 0.13,
    gravityFieldRadius: 190,
    gravityFlipDamping: 0.45,
    gravityFieldDuration: 3.5,
    timeSlowRadius: 260,
    timeSlowDuration: 2.75,
    timeSlowCooldown: 7.0,
    timeSlowMultiplier: 0.4,
    forcePulseRange: 280,
    forcePulseKnockback: 780,
    forcePulseStun: 0.18,
    forcePulseVisualDuration: 0.14,
    forcePulseExpandDuration: 0.07,
    forcePulseArmPushDuration: 0.15,
    forcePulseArmRecoveryDuration: 0.13,
    forcePulseCooldown: 4.0,
    contactDamageCooldown: 0.8,
    fallBoundaryOffset: 48,
    fallRespawnGrace: 0.22,
    edgeRespawnInset: 18,
    roomWidth: 2200,
    checkpoint: { x: 86, y: 362 },
    safeAnchor: { x: 92, y: 362 }
  });
})();
